// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer env vars; fall back to the previously configured public project to avoid dev crashes
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string) || "https://txfqrwyqowbcngugytyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY as string) || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4ZnFyd3lxb3diY25ndWd5dHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0Mzc3NzAsImV4cCI6MjA3MjAxMzc3MH0.CzZGNgH6lorEO3KJZ3YDlJ_iiNETovytDmcgTXYq1NM";

if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY) {
  console.warn('[Supabase] Using fallback public credentials. For your own project, set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in a .env file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});